### PR TITLE
update-icon-and-desktop-file

### PR DESCRIPTION
**Pull request by dominikzogg**
besides updating the icons, the change in the .desktop file allows to put in mongodb:// urls in the browser and it opens via mongodb compass

### CODE REVIEW

**Comment by mijorus** [comment]
This app should not have the Gtk and the GNOME category, as it's made with Electron.

If something, you could add "Database"

https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry

**Comment by dominikzogg** [comment]
@mijorus its from the original package, they provide this .desktop file

**Comment by mijorus** [comment]
> @mijorus its from the original package, they provide this .desktop file

Lol. All right leave it as it is.

**Comment by dominikzogg** [comment]
@mijorus in the .deb, i extracted it from there. Still i i will add Database when i am at my computer.

**Pull request merged**
